// <auto-generated />
using System;
using Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace PMAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190117012331_initdb")]
    partial class initdb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Domain.CodeMap", b =>
                {
                    b.Property<string>("Key")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<string>("ChineseName")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CodeName")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description")
                        .HasMaxLength(256);

                    b.Property<string>("Lower")
                        .HasMaxLength(32);

                    b.Property<DateTime?>("RemovedOn");

                    b.Property<int>("Seq");

                    b.Property<int>("Status");

                    b.Property<DateTime?>("UpdatedOn");

                    b.Property<string>("Upper")
                        .HasMaxLength(32);

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Key");

                    b.ToTable("CodeMaps");
                });
#pragma warning restore 612, 618
        }
    }
}
